version: "3.9"
services:
  rubinot:
    restart: on-failure
    build: .
    environment:
      - SERVER_PORT=5000
    ports:
      - "81:5000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rubinot
