version: "3.9"
services:
  cache:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  rubinot:
    restart: on-failure
    build: .
    ports:
      - "81:5000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rubinot
